### ISSUE TITLE
Example suggestion

### ISSUE THREAD

**Issue by Whyounes** [tagtree/expert-es6#4]
On the Expert ES6 course part 10, the example can template string when saying "hi name".

**Comment by hendrikswan** [comment]
Feel free to do create a fork, make the change, and then do a pull request!

**Comment by Whyounes** [comment]
The exercises are not present on the repo.

**Comment by hendrikswan** [comment]
Oh, right, I wasn't sure what you meant with example. Bummer.
Perhaps you can find something to improve in the instructional stuff that
is available in the repo?
